# Generated by Django 3.0.6 on 2020-05-13 17:29

import app.models.lesson
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lecture',
            field=models.FileField(blank=True, null=True, upload_to=app.models.lesson.upload_location, verbose_name='Лекция'),
        ),
    ]
