# Generated by Django 3.0.6 on 2020-05-15 18:24

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200515_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lecture',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
    ]
