# Generated by Django 3.0.6 on 2020-05-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200515_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='answer',
            field=models.FileField(upload_to='media/', verbose_name='Домашняя работа'),
        ),
    ]
