# Generated by Django 3.0.6 on 2020-05-16 04:32

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200516_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='answer',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Домашняя работа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
