# Generated by Django 3.0.6 on 2020-05-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200516_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='mark',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
